import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { ArrowRight, FileUp, Gift, LogIn, PenLine, Sparkles } from "lucide-react";
import { Link, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";

const choices = [
  { id: "upload", eyebrow: "Already have a story?", title: "Upload your PDF", detail: "Bring your CV or portfolio document. We'll keep it safe while you shape the next version.", icon: FileUp, tone: "bg-[#e4f18e]", action: "Continue with a document" },
  { id: "scratch", eyebrow: "Starting fresh?", title: "Start from scratch", detail: "Choose a visual direction, add your work, and leave with a portfolio that feels like you.", icon: PenLine, tone: "bg-[#f6c6a7]", action: "Build my portfolio" },
  { id: "refer", eyebrow: "Know someone building?", title: "Refer & earn ₦100", detail: "Share Presently with a friend. When they publish their portfolio, you earn ₦100—no clickbait, no shortcuts.", icon: Gift, tone: "bg-[#b9d8c5]", action: "See how it works" },
];

export default function Home() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const choose = (choice: string) => {
    if (choice === "refer") return;
    if (choice === "scratch" && user) return setLocation("/editor");
    localStorage.setItem("presently-intent", choice);
    startLogin();
  };
  return <div className="min-h-screen overflow-hidden bg-[#f8f5ed]">
    <header className="container flex items-center justify-between py-6"><Link href="/" className="display-font text-xl font-bold tracking-[-.06em]">presently<span className="text-[#e98d55]">.</span></Link><div className="flex items-center gap-3 text-sm"><span className="hidden text-[#6f786f] sm:block">Your work deserves a place to land.</span>{loading ? null : user ? <Link href="/editor" className="inline-flex items-center gap-2 rounded-full border border-[#dedcd2] bg-white/60 px-4 py-2 font-semibold text-[#21473a]">Open editor <ArrowRight className="h-4 w-4" /></Link> : <Button onClick={() => startLogin()} variant="ghost" className="gap-2 text-[#21473a]"><LogIn className="h-4 w-4" /> Sign in</Button>}</div></header>
    <main className="container pb-20 pt-10 md:pt-20"><section className="relative grid items-end gap-10 lg:grid-cols-[1.08fr_.92fr]"><div className="relative z-10 max-w-3xl fade-up"><div className="mb-8 inline-flex items-center gap-2 rounded-full border border-[#dedcd2] bg-white/55 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.18em] text-[#6f786f]"><Sparkles className="h-3.5 w-3.5 text-[#e98d55]" /> A calmer way to show your work</div><h1 className="display-font max-w-3xl text-6xl font-bold leading-[.93] tracking-[-.07em] text-[#21473a] md:text-8xl">Present your work<br /><span className="text-[#e98d55]">and professional identity.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#6f786f]">A considered portfolio builder for developers, designers, students, freelancers, and the quietly ambitious.</p></div><div className="relative min-h-[220px] overflow-hidden rounded-[2rem] bg-[#21473a] p-7 text-[#f8f5ed] shadow-xl fade-up-delay"><div className="absolute -right-12 -top-12 h-44 w-44 rounded-full border-[18px] border-[#e4f18e]/80" /><div className="absolute -bottom-20 -left-8 h-48 w-48 rounded-full bg-[#e98d55]/80 blur-[1px]" /><div className="relative flex h-full flex-col justify-between"><p className="max-w-[220px] text-2xl leading-8">The internet is full of noise. Your portfolio doesn't have to be.</p><div className="mt-8 flex items-center justify-between border-t border-white/15 pt-4 text-xs uppercase tracking-[.18em] text-white/55"><span>Presently, 2026</span><span>01 / 05</span></div></div></div></section>
    <section className="mt-20" id="choices"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#e98d55]">Choose your beginning</p><h2 className="display-font mt-2 text-2xl font-bold text-[#21473a]">Three ways in. One place to grow.</h2></div><span className="hidden text-sm text-[#6f786f] sm:block">No website maintenance required.</span></div><div className="grid gap-4 lg:grid-cols-3">{choices.map(({ id, eyebrow, title, detail, icon: Icon, tone, action }) => <div key={id} className="group flex min-h-[280px] flex-col rounded-[1.5rem] border border-[#dedcd2] bg-white/65 p-6 shadow-[0_8px_0_rgba(33,71,58,.03)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_18px_35px_rgba(33,71,58,.08)]"><div className={`mb-8 flex h-12 w-12 items-center justify-center rounded-2xl ${tone} text-[#21473a]`}><Icon className="h-5 w-5" /></div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#6f786f]">{eyebrow}</p><h3 className="display-font mt-2 text-2xl font-bold text-[#21473a]">{title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-[#6f786f]">{detail}</p><div className="mt-auto pt-7">{id === "refer" ? <Link href="/refer" className="inline-flex items-center gap-2 text-sm font-bold text-[#21473a]">{action}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link> : <button onClick={() => choose(id)} className="inline-flex items-center gap-2 text-sm font-bold text-[#21473a]">{action}<ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></button>}</div></div>)}</div></section>
    <section className="mt-20 grid gap-6 border-t border-[#dedcd2] pt-8 text-sm text-[#6f786f] md:grid-cols-3"><div><span className="font-bold text-[#21473a]">01 / Curated templates</span><p className="mt-2 leading-6">Five visual directions, one data model. Change your look without rewriting your story.</p></div><div><span className="font-bold text-[#21473a]">02 / Yours to share</span><p className="mt-2 leading-6">Publish a clean public link that works on mobile and desktop.</p></div><div><span className="font-bold text-[#21473a]">03 / Built with integrity</span><p className="mt-2 leading-6">Referral rewards happen after real work is published—not after a click.</p></div></section></main>
  </div>;
}
